[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

  from = "/*/*"
  to = "/index.html"
  status = 404

    from = "/*/*/*"
  to = "/index.html"
  status = 404

    from = "/*/*/*/*"
  to = "/index.html"
  status = 404

    from = "/*/*/*/*/*"
  to = "/index.html"
  status = 404